// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'db/connection.dart';
import 'db/entities.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

abstract class Sender {
  Future<void> sendNewsgroup({required NewsGroup newsgroup});

  Future<void> sendPost({required Posts post, required SubrosaDb db});
}
